apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:  
   server: <IP_ADDRESS>
   path: /home/ubuntu/nfs-share
---