apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      key: mypod
  template:
    metadata:
      labels:
        key: mypod
    spec:
      containers:
        - name: mycontainer
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: myvolume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: myvolume
          persistentVolumeClaim:  
            claimName: mypvc
