apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      key: mypod
  template:
    metadata:
      labels:
        key: mypod
    spec:
      containers:
        - name: mycontainer
          image: nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
               httpGet:
                  path: /login.html
                  port: 80
               initialDelaySecond: 5
               periodSeconds: 10
               timeoutSeconds: 3
               failureThereshold: 3